### ISSUE TITLE
Position in the output signature correspondence

### ISSUE THREAD

**Issue by StefanStanisor** [bottler/phd-docs#1]
How can we infer the iterated integral that is on position i in the output signature?
i.e. suppose we have a path of dimension (5, 2). Then the signature should have size 6, but which position corresponds to the iterated integral 12 for example?

**Comment by bottler** [comment]
Are you asking about `iisignature` specifically (whose doc is here)  or something else?

And what do you mean by "path of dimension (5, 2)"? ~A path of dimension 5's signature up to level 2, and a path of dimension 2's signature up to level 5 both have size 30 (omittting level zero).~ [EDIT: that's not correct.] 

In iisignature, the elements of a signature of a 2d path up to level 2 should be `1, 2, 11, 12, 21, 22` - this might answer your question.

**Comment by StefanStanisor** [comment]
Yes, lexicographic order answers my question, thanks!
